### ISSUE TITLE
Unable to convert MAME Bezels to Retroarch when they are vertical Bezels

### ISSUE THREAD

**Issue by mickael28** [cosmo0/mame-retroarch-bezel-converter#1]
Hi @cosmo0 , thanks for the tool, I've been trying to use it for a while but I'm getting a few errors. 

I've got the following MAME Bezel, which is Vertical:
[ddonpach.zip](https://github.com/cosmo0/mame-retroarch-bezel-converter/files/7921687/ddonpach.zip)

If I run the following command to convert it to a Retroarch Bezel, I'm getting the following errors:
```
 ./bezel-tools.exe mtr --source ../BezelRealisticZIP/ --output-roms ../../emulators/mame/cfgRetroarch/ --output-overlays ../BezelRealisticFromMAME/ --template-game templates/game.cfg --template-overlay templates/overlay.cfg
```

* Issue 1 - when the MAME bezel is not a zip file, but a folder instead (with the pngs and lay files inside):
``` ddonpach PROCESSING ERROR: Unable to find the bezel file System.String[]```
Workaround 1 - zip the files into a zip and try again

* Issue 2 when rerunning the command:
``` ddonpach PROCESSING ERROR: Unable to find file ..\DefaultBezelH.png in archive ```
I checked all files in a working setup of MAME and there's no `DefaultBezelH.png` file anywhere, it seems as if the file is not used at all, even though it's in the .lay file (but the MAME setup works without it)

* Issue 3, with a first Workaround tried for 2: 
I tried to delete that section from the lay file
```
Deleted:
 <element name="Glass">
    <image file="..\DefaultBezelH.png"/>
  </element>
```
so got the error:
```
ddonpach PROCESSING ERROR: Unable to find element with name Glass in LAY file
```

* Issue 4, when a second Workaround tried for 2:
I added a different file that I found in the working setup inside the ddonpach.zip file with:
```
 <element name="Glass">
    <image file="BezelLightGlass.png"/>
  </element>
```
This was that new file: 
[ddonpach.zip](https://github.com/cosmo0/mame-retroarch-bezel-converter/files/7921693/ddonpach.zip)

Final error where I got stuck:
```
ddonpach doesn't have a cfg file
ddonpach PROCESSING ERROR: Bezel of view Bezel does not have coordinates starting at (0,0)
```

I don't understand these files much yet, so I mentioned Issues 1, 2 and 3 in case they're useful to handle them if those files are not required or the tool could check folders rather than zip files for MAME bezels, but the main issue I'm reporting (which is where I'm currently stuck) is `Issue 4`, do you know why I could be getting those errors?

The 1st one in that line is mentioning that:
* `ddonpach doesn't have a cfg file` - but I thought the CFG file for Retroarch is what this tool was going to create, is it not?
* `ddonpach PROCESSING ERROR: Bezel of view Bezel does not have coordinates starting at (0,0)` - this one is mentioning and error due to coordinates (0, 0), not sure if this is because the bezels are vertical?

Could you see if it's something you can handle with the code in your end pls and let me know if I could try a new release? 
or if you've got any suggestion about how I could re-run the command, pls let me know and I'll report how it goes?

Many thanks!

**Comment by cosmo0** [comment]
Hi! I'm sorry, I know I'm (very) late. I've pushed a new release which should hopefully fix your problem. Please let me know!

https://github.com/cosmo0/mame-retroarch-bezel-converter/releases/tag/v3.3
